name: SampleApp
options:
  xcodeVersion: "15.0"
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: 5.0

packages:
  SampleApp:
    path: .

targets:
  SampleApp:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.sample.${PRODUCT_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        GENERATE_INFOPLIST_FILE: true
        ENABLE_USER_SCRIPT_SANDBOXING: false
        INFOPLIST_KEY_CFBundleDisplayName: ${PRODUCT_NAME}
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen.storyboard
        INFOPLIST_KEY_UISupportedInterfaceOrientations:        
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    sources:
      - path: ./App/iOS
    dependencies:
      - package: SampleApp
        products:
          - App
    postBuildScripts:
      - name: Run SwiftLint
        path: /bin/sh
        script: |-
          cd $SRCROOT/..

          make lint

schemes:
  SampleApp:
    build:
      targets:
        SampleApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Debug